In [65]:
from square.client import Client
import os
import pandas as pd

from google_sheets import *

# import pandas as pd
from boto import get_square_secret

# import os
import pickle

# Get OPTI Sheet

In [66]:
SAMPLE_SPREADSHEET_ID_input = '1lalOwWx_GwUZgjG3WgyxZvirtT9GYDJ6t3dAuNimTLM'
SHEETS = ['1s Sheet!A1:AA17','2s Sheet!A1:AA17','3s Sheet!A1:AA17','4s Sheet!A1:AA17','5s Sheet!A1:AA17','6s Sheet!A1:AA17','Vets!A1:AA17']

In [67]:
dfs=[get_spread_sheet(SAMPLE_SPREADSHEET_ID_input, sheet) for sheet in SHEETS]
df = pd.concat(dfs)

In [68]:
df=df[df['Check']=='TRUE']

In [69]:
df['Competition']=df['Competition'].apply(lambda x: 'Cup' if 'cup' in x.lower() else x)

In [72]:
df['Competition']=df['Competition'].apply(lambda x: 'Cup' if 'cup' in x.lower() else x)
comps=df[['OT Team', 'Competition']].drop_duplicates()
comps

  OT Team Competition
0       1      League
0       2      League
0       3         Cup
0       4
0       5
0       6
0    Vets

In [74]:
comps_to_update={'4':'League', '5':'League', '6':'Cup', 'Vets':'Cup'}

In [75]:
df['Competition']=df.apply(lambda row: comps_to_update[row['OT Team']] if row['OT Team'] in comps_to_update else row['Competition'], axis =1)

In [76]:
comps=df[['OT Team', 'Competition']].drop_duplicates()
comps

  OT Team Competition
0       1      League
0       2      League
0       3         Cup
0       4      League
0       5      League
0       6         Cup
0    Vets         Cup

In [77]:
df['Match Date']=pd.to_datetime(df['Match Date']).apply(lambda x:x.strftime('%d %b'))
df['Match Date']

0     07 Oct
1     07 Oct
2     07 Oct
3     07 Oct
4     07 Oct
       ...
10    07 Oct
11    07 Oct
12    07 Oct
13    07 Oct
14    07 Oct
Name: Match Date, Length: 96, dtype: object

In [78]:
df['identifier']=df['Match Date']+'-'+df['OT Team']

In [79]:
df

,Player Name,Position,OT Team,Opposition Name,Result,Goals,Assists,Goals Conceded,Yellow Cards,Sin Bin,...,Match day rating,Comments,Formation,Team Report,Score for,Score against,Competition,Match Date,Check,identifier
0,John Harrison,GK,1,HAC,Loss,,,3,,,...,8,"Nice pen save, went short too often when we ha...",3-5-2,Opening 20 mins was very scrappy from both tea...,1,3,League,07 Oct,TRUE,07 Oct-1
1,Matt Crowe,CB,1,HAC,Loss,,,3,,,...,7.5,Not quite at his best. Poor losing the header...,3-5-2,Opening 20 mins was very scrappy from both tea...,1,3,League,07 Oct,TRUE,07 Oct-1
2,Aaron Snelling,CB,1,HAC,Loss,,,3,,,...,5,"Sending off incident sort of not his fault, st...",3-5-2,Opening 20 mins was very scrappy from both tea...,1,3,League,07 Oct,TRUE,07 Oct-1
3,Theo Horton,CB,1,HAC,Loss,,,3,,,...,9,What a guy. Supeb game and legend for going i...,3-5-2,Opening 20 mins was very scrappy from both tea...,1,3,League,07 Oct,TRUE,07 Oct-1
4,Ben Dockerill,RWB,1,HAC,Loss,,,3,1,,...,7,He got close on the MOTM votes. I thought it ...,3-5-2,Opening 20 mins was very scrappy from both tea...,1,3,League,07 Oct,TRUE,07 Oct-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,Ash Mayers,,Vets,,Draw,,,,,,...,,,,,,,Cup,07 Oct,TRUE,07 Oct-Vets
11,Andrew Barclay,,Vets,,Draw,,,,,,...,,,,,,,Cup,07 Oct,TRUE,07 Oct-Vets
12,Jack Butcher,,Vets,,Draw,,,,,,...,,,,,,,Cup,07 Oct,TRUE,07 Oct-Vets
13,Paul Jalil,,Vets,,Draw,,,,,,...,,,,,,,Cup,07 Oct,TRUE,07 Oct-Vets
14,Deji Ogunyemi,,Vets,,Draw,,,,,,...,,,,,,,Cup,07 Oct,TRUE,07 Oct-Vets

# GET OPTI DB

In [80]:
SHEET = 'OTPI Scores!A:AC'

In [81]:
opti_db = get_spread_sheet(SAMPLE_SPREADSHEET_ID_input, SHEET)

In [82]:
opti_db

,Game Date,Competition,Player Name,Position,OT Team,Opposition Name,Result,Goals,Assists,Goals Conceded,...,Amount Owed,Match day rating,Comments,Formation,Team Report,Score For,Score Against,OPTI Score,Missing,This Week
0,5 Aug,Friendly,Nima Naghdi,MID,4,Thorns Yellow,WIN,,,0,...,0,,,,,,,9,FALSE,0.00
1,5 Aug,Friendly,James Bashford,DEF,4,Thorns Yellow,WIN,,,0,...,5,,,,,,,8,FALSE,0.00
2,5 Aug,Friendly,Oli Barton,DEF,4,Thorns Yellow,WIN,,,0,...,10,,,,,,,8,FALSE,0.00
3,5 Aug,Friendly,Andreas Andreou,DEF,4,Thorns Yellow,WIN,,,0,...,10,,,,,,,8,FALSE,0.00
4,5 Aug,Friendly,Tom Love,DEF,4,Thorns Yellow,WIN,,,0,...,10,,,,,,,8,FALSE,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,30 Sep,Friendly,Ash Mayers,,Vets,,Draw,,,,...,10,,,,,,,2,FALSE,1.00
674,30 Sep,Friendly,Rich Lundie,,Vets,,Draw,,,,...,10,,,,,,,2,FALSE,1.00
675,30 Sep,Friendly,Stu Jordan,,Vets,,Draw,,,,...,10,,,,,,,2,FALSE,1.00
676,30 Sep,Friendly,Phil Boden,,Vets,,Draw,,,,...,10,,,,,,,2,FALSE,1.00
677,30 Sep,Friendly,Jack Butcher,,Vets,,Draw,,,,...,10,,,,,,,2,FALSE,1.00

In [83]:
opti_db['identifier']=opti_db['Game Date']+'-'+opti_db['OT Team']

In [84]:
opti_db

,Game Date,Competition,Player Name,Position,OT Team,Opposition Name,Result,Goals,Assists,Goals Conceded,...,Match day rating,Comments,Formation,Team Report,Score For,Score Against,OPTI Score,Missing,This Week,identifier
0,5 Aug,Friendly,Nima Naghdi,MID,4,Thorns Yellow,WIN,,,0,...,,,,,,,9,FALSE,0.00,5 Aug-4
1,5 Aug,Friendly,James Bashford,DEF,4,Thorns Yellow,WIN,,,0,...,,,,,,,8,FALSE,0.00,5 Aug-4
2,5 Aug,Friendly,Oli Barton,DEF,4,Thorns Yellow,WIN,,,0,...,,,,,,,8,FALSE,0.00,5 Aug-4
3,5 Aug,Friendly,Andreas Andreou,DEF,4,Thorns Yellow,WIN,,,0,...,,,,,,,8,FALSE,0.00,5 Aug-4
4,5 Aug,Friendly,Tom Love,DEF,4,Thorns Yellow,WIN,,,0,...,,,,,,,8,FALSE,0.00,5 Aug-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,30 Sep,Friendly,Ash Mayers,,Vets,,Draw,,,,...,,,,,,,2,FALSE,1.00,30 Sep-Vets
674,30 Sep,Friendly,Rich Lundie,,Vets,,Draw,,,,...,,,,,,,2,FALSE,1.00,30 Sep-Vets
675,30 Sep,Friendly,Stu Jordan,,Vets,,Draw,,,,...,,,,,,,2,FALSE,1.00,30 Sep-Vets
676,30 Sep,Friendly,Phil Boden,,Vets,,Draw,,,,...,,,,,,,2,FALSE,1.00,30 Sep-Vets
677,30 Sep,Friendly,Jack Butcher,,Vets,,Draw,,,,...,,,,,,,2,FALSE,1.00,30 Sep-Vets

# Merge

In [85]:
mg=pd.merge(left=opti_db, right=df, how='outer', on=['identifier'], suffixes=['_db', ''])

In [86]:
to_append=mg[mg['Game Date'].isnull()][df.columns]

In [87]:
to_append['Game Date']=to_append['Match Date']

# Add Formulas

In [88]:
curr_rows=len(opti_db)+1

In [89]:
opti_formula='''=2+ (P{rn}*'Scoring System'!$B$3)+ (IF(OR(D{rn}="DEF",D{rn}="GK"),N{rn}*'Scoring System'!$B$4,IF(D{rn}="MID",N{rn}*'Scoring System'!$B$5,0)))+ (IF(OR(D{rn}="DEF",D{rn}="GK"),H{rn}*'Scoring System'!$B$6,IF(D{rn}="MID",H{rn}*'Scoring System'!$B$7,IF(D{rn}="ATT",H{rn}*'Scoring System'!$B$8,0))))+ IF(AND(OR(D{rn}="GK",D{rn}="DEF"),J{rn}>=3),1*'Scoring System'!$B$9,0)+ (I{rn}*'Scoring System'!$B$10)+ (K{rn}*'Scoring System'!$B$11)+ (M{rn}*'Scoring System'!$B$12)+ (L{rn}*'Scoring System'!$B$13)+ (O{rn}*'Scoring System'!$B$14)+ (Q{rn}*'Scoring System'!$B$15)+ (R{rn}*'Scoring System'!$B$16)'''
missing_formula='''=IFERROR(match(C{rn},'Match Day Fees'!$B$2:$B$999,0),0)=0'''
week_formula='''=IF(max(A:A)=A{rn},1,0)'''

In [90]:
to_append['row']=range(len(to_append))
to_append['row']=to_append['row']+curr_rows+1

In [91]:
to_append['OPTI Score']=to_append['row'].apply(lambda x: opti_formula.format(rn=x))
to_append['Missing']=to_append['row'].apply(lambda x: missing_formula.format(rn=x))
to_append['This Week']=to_append['row'].apply(lambda x: week_formula.format(rn=x))

In [92]:
to_append

,Player Name,Position,OT Team,Opposition Name,Result,Goals,Assists,Goals Conceded,Yellow Cards,Sin Bin,...,Score against,Competition,Match Date,Check,identifier,Game Date,row,OPTI Score,Missing,This Week
678,John Harrison,GK,1,HAC,Loss,,,3,,,...,3,League,07 Oct,TRUE,07 Oct-1,07 Oct,680,=2+ (P680*'Scoring System'!$B$3)+ (IF(OR(D680=...,"=IFERROR(match(C680,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A680,1,0)"
679,Matt Crowe,CB,1,HAC,Loss,,,3,,,...,3,League,07 Oct,TRUE,07 Oct-1,07 Oct,681,=2+ (P681*'Scoring System'!$B$3)+ (IF(OR(D681=...,"=IFERROR(match(C681,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A681,1,0)"
680,Aaron Snelling,CB,1,HAC,Loss,,,3,,,...,3,League,07 Oct,TRUE,07 Oct-1,07 Oct,682,=2+ (P682*'Scoring System'!$B$3)+ (IF(OR(D682=...,"=IFERROR(match(C682,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A682,1,0)"
681,Theo Horton,CB,1,HAC,Loss,,,3,,,...,3,League,07 Oct,TRUE,07 Oct-1,07 Oct,683,=2+ (P683*'Scoring System'!$B$3)+ (IF(OR(D683=...,"=IFERROR(match(C683,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A683,1,0)"
682,Ben Dockerill,RWB,1,HAC,Loss,,,3,1,,...,3,League,07 Oct,TRUE,07 Oct-1,07 Oct,684,=2+ (P684*'Scoring System'!$B$3)+ (IF(OR(D684=...,"=IFERROR(match(C684,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A684,1,0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769,Ash Mayers,,Vets,,Draw,,,,,,...,,Cup,07 Oct,TRUE,07 Oct-Vets,07 Oct,771,=2+ (P771*'Scoring System'!$B$3)+ (IF(OR(D771=...,"=IFERROR(match(C771,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A771,1,0)"
770,Andrew Barclay,,Vets,,Draw,,,,,,...,,Cup,07 Oct,TRUE,07 Oct-Vets,07 Oct,772,=2+ (P772*'Scoring System'!$B$3)+ (IF(OR(D772=...,"=IFERROR(match(C772,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A772,1,0)"
771,Jack Butcher,,Vets,,Draw,,,,,,...,,Cup,07 Oct,TRUE,07 Oct-Vets,07 Oct,773,=2+ (P773*'Scoring System'!$B$3)+ (IF(OR(D773=...,"=IFERROR(match(C773,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A773,1,0)"
772,Paul Jalil,,Vets,,Draw,,,,,,...,,Cup,07 Oct,TRUE,07 Oct-Vets,07 Oct,774,=2+ (P774*'Scoring System'!$B$3)+ (IF(OR(D774=...,"=IFERROR(match(C774,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A774,1,0)"
773,Deji Ogunyemi,,Vets,,Draw,,,,,,...,,Cup,07 Oct,TRUE,07 Oct-Vets,07 Oct,775,=2+ (P775*'Scoring System'!$B$3)+ (IF(OR(D775=...,"=IFERROR(match(C775,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A775,1,0)"

#  Get Columns

In [93]:
cols = ['Game Date',
        'Competition',
        'Player Name',
        'Position',
        'OT Team',
        'Opposition Name',
        'Result',	
        'Goals',	
        'Assists',	
        'Goals Conceded',	
        'Yellow Cards',	
        'Sin Bin',	
        'Red Cards',	
        'Clean Sheet?',	
        'Penalties Missed',	
        'Penalties Saved',	
        'Own Goals',	
        'MOTM?',	
        'Kit',	
        'Amount Owed',	
        'Match day rating',	
        'Comments',	
        'Formation',	
        'Team Report',	
        'Score for',
        'Score against',
        'OPTI Score',
        'Missing',
        'This Week'
]

In [94]:
to_append=to_append[cols].copy()

# Mapping

In [96]:
to_append['Position'].drop_duplicates()

678     GK
679     CB
682    RWB
683    LWB
684     CM
687     CF
693    RCB
696    LCB
697     LW
702     RW
703     RB
705    DCM
710     LB
725    ACM
759
Name: Position, dtype: object

In [100]:
position_map = {
'GK':'GK',
'CB':'DEF',
'RWB':'DEF',
'LWB':'DEF',
'CM':'MID',
'CF':'ATT',
'RCB':'DEF',
'LCB':'DEF',
'LW':'ATT',
'RW':'ATT',
'RB':'DEF',
'DCM':'MID',
'LB':'DEF',
'ACM':'MID'
,'':''
}

In [101]:
to_append['Position']=to_append['Position'].apply(lambda x: position_map[x])

In [102]:
to_append['Position'].drop_duplicates()

678     GK
679    DEF
684    MID
687    ATT
759
Name: Position, dtype: object

In [103]:
to_append[to_append['Position']=='']

,Game Date,Competition,Player Name,Position,OT Team,Opposition Name,Result,Goals,Assists,Goals Conceded,...,Amount Owed,Match day rating,Comments,Formation,Team Report,Score for,Score against,OPTI Score,Missing,This Week
759,07 Oct,Cup,Victor Lemmer,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P761*'Scoring System'!$B$3)+ (IF(OR(D761=...,"=IFERROR(match(C761,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A761,1,0)"
760,07 Oct,Cup,Chris Boden,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P762*'Scoring System'!$B$3)+ (IF(OR(D762=...,"=IFERROR(match(C762,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A762,1,0)"
761,07 Oct,Cup,Phil Boden,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P763*'Scoring System'!$B$3)+ (IF(OR(D763=...,"=IFERROR(match(C763,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A763,1,0)"
762,07 Oct,Cup,Dean Wright,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P764*'Scoring System'!$B$3)+ (IF(OR(D764=...,"=IFERROR(match(C764,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A764,1,0)"
763,07 Oct,Cup,Matt Powell,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P765*'Scoring System'!$B$3)+ (IF(OR(D765=...,"=IFERROR(match(C765,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A765,1,0)"
764,07 Oct,Cup,Jason Raife,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P766*'Scoring System'!$B$3)+ (IF(OR(D766=...,"=IFERROR(match(C766,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A766,1,0)"
765,07 Oct,Cup,Jamie Arkell,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P767*'Scoring System'!$B$3)+ (IF(OR(D767=...,"=IFERROR(match(C767,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A767,1,0)"
766,07 Oct,Cup,Steve Francis,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P768*'Scoring System'!$B$3)+ (IF(OR(D768=...,"=IFERROR(match(C768,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A768,1,0)"
767,07 Oct,Cup,Richard Lundie,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P769*'Scoring System'!$B$3)+ (IF(OR(D769=...,"=IFERROR(match(C769,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A769,1,0)"
768,07 Oct,Cup,Ste Calder,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P770*'Scoring System'!$B$3)+ (IF(OR(D770=...,"=IFERROR(match(C770,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A770,1,0)"
769,07 Oct,Cup,Ash Mayers,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P771*'Scoring System'!$B$3)+ (IF(OR(D771=...,"=IFERROR(match(C771,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A771,1,0)"
770,07 Oct,Cup,Andrew Barclay,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P772*'Scoring System'!$B$3)+ (IF(OR(D772=...,"=IFERROR(match(C772,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A772,1,0)"
771,07 Oct,Cup,Jack Butcher,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P773*'Scoring System'!$B$3)+ (IF(OR(D773=...,"=IFERROR(match(C773,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A773,1,0)"
772,07 Oct,Cup,Paul Jalil,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P774*'Scoring System'!$B$3)+ (IF(OR(D774=...,"=IFERROR(match(C774,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A774,1,0)"
773,07 Oct,Cup,Deji Ogunyemi,,Vets,,Draw,,,,...,10,,,,,,,=2+ (P775*'Scoring System'!$B$3)+ (IF(OR(D775=...,"=IFERROR(match(C775,'Match Day Fees'!$B$2:$B$9...","=IF(max(A:A)=A775,1,0)"

# Append

In [104]:
result=append_to_sheet_temp('OTPI Scores!A:AC', SAMPLE_SPREADSHEET_ID_input, to_append)

In [106]:
96.5+100+98+100+115+105+150

764.5